### ISSUE TITLE
USB Support

### ISSUE THREAD

**Issue by Surge2S** [KingLycosa/acnhpoker#9]
It would be really nice to have usb support for the next release! To avoid connecting online for those of us that like to keep this offline only.

**Comment by yakobie** [comment]
This currently isn't something I am looking to add. I rely heavily on the API provided by botbase, the switch doesn't have to connect to the internet to connect to your Wi-Fi. Sorry!

**Comment by datiecher** [comment]
Would you reconsider implementing this feature since there's a fork of sys-botbase that uses the same interface but communicates over USB? The project in question is [USB-Botbase](https://github.com/fishguy6564/USB-Botbase). One of the reasons for using an USB cable instead of a Wi-Fi connection is for those of us who have a bad router that something craps the bed when you're using it.

**Comment by yakobie** [comment]
no, people are already using my program to make money en masse. I am not going to make it even easier for them. It is a very easy implementation and I don't really want to spoonfeed others profiting off of users who aren't running CFW.
